CREATE DATABASE UNIQLOb8
GO
USE UNIQLOb8
GO

CREATE TABLE  Staff (
	 StaffID   CHAR (4) NOT NULL PRIMARY KEY,
	 StaffName   NVARCHAR (8) NOT NULL,
	 Sex   CHAR (2) NOT NULL
 )
GO
INSERT INTO Staff
VALUES
('1000','张三','男'),
('2000','李四','男'),
('3000','王五','女')
GO

CREATE TABLE [Role](
	 RoleID   CHAR (1) NOT NULL PRIMARY KEY,
	 RoleName   NVARCHAR (20) NOT NULL
) 
GO
INSERT INTO [Role]
VALUES
('1','进货员'),
('2','收银员'),
('3','店长')
GO

CREATE TABLE [User](
	 UserID   CHAR(4)  NOT NULL PRIMARY KEY,
	 StaffID   CHAR (4) NOT NULL,
	 RoleID   CHAR (1) NOT NULL,
	 PWD   NVARCHAR (20) DEFAULT('123'),
	 FOREIGN KEY(RoleID) REFERENCES Role(RoleID),
	 FOREIGN KEY(StaffID) REFERENCES Staff(StaffID)
)
GO
INSERT INTO [User]
VALUES
('1001','1000','1','123'),
('2001','2000','2','123'),
('3001','3000','3','123')
GO

CREATE TABLE Good(
GoodID NVARCHAR(50) NOT NULL PRIMARY KEY,
GoodName NVARCHAR(255) NOT NULL,
GoodColor NVARCHAR(20),
GoodSize NVARCHAR(3),
GoodPrice NUMERIC(4,2) NOT NULL,
GoodNum INT NOT NULL,
Operator CHAR(4) NOT NULL,
CONSTRAINT  CK_Good CHECK (LEN(GoodName)>0 AND LEN(GoodPrice)>0 AND LEN(GoodNum)>0 AND LEN(Operator)>0 AND GoodNum>=0 AND GoodPrice>=0),
FOREIGN KEY (Operator) REFERENCES Staff(StaffID)
)
GO

CREATE TABLE Bill(
BillID NVARCHAR(50) NOT NULL PRIMARY KEY,
SaleTime DATETIME NOT NULL,
GoodID NVARCHAR(50) NOT NULL,
GoodName NVARCHAR(255) NOT NULL,
GoodColor NVARCHAR(20),
GoodSize NVARCHAR(3),
BuyGoodNum INT NOT NULL,
GoodPrice NUMERIC(4,2) NOT NULL,
GoodTotalPrice NUMERIC(6,2) NOT NULL,
BillSatuts NVARCHAR(4) NOT NULL DEFAULT '正常',
Operator CHAR(4) NOT NULL,
CONSTRAINT  CK_Bill CHECK (LEN(SaleTime)>0 AND LEN(GoodID)>0 AND LEN(GoodName)>0 AND LEN(BuyGoodNum)>0 AND 
LEN(GoodPrice)>0 AND LEN(GoodTotalPrice)>0 AND LEN(Operator)>0 AND BuyGoodNum>0 AND GoodPrice>=0 AND GoodTotalPrice>=GoodPrice),
FOREIGN KEY (Operator)  REFERENCES Staff(StaffID)
)
GO

CREATE TABLE Aftersale(
ReID NVARCHAR(50) NOT NULL PRIMARY KEY,
BillID NVARCHAR(50) NOT NULL UNIQUE,
SaleTime DATETIME NOT NULL,
ReTime DATETIME NOT NULL,
ReType NVARCHAR(4) NOT NULL,
ReGoodID NVARCHAR(50) NOT NULL,
ReGoodName NVARCHAR(255) NOT NULL,
ReGoodNum INT NOT NULL,
ReMoney NUMERIC(6,2),
Operator CHAR(4) NOT NULL,
CONSTRAINT CK_ReGood CHECK(LEN(ReID)>0 AND LEN(SaleTime)>0 AND LEN(ReTime)>0 AND LEN(ReGoodID)>0 AND 
LEN(ReGoodName)>0 AND LEN(ReGoodNum)>0 AND LEN(Operator)>0 AND ReGoodNum>0),
FOREIGN KEY (Operator)  REFERENCES Staff(StaffID)
)
GO

--CREATE TABLE ExgGood(
--ExgID NVARCHAR(50) NOT NULL PRIMARY KEY,
--BillID NVARCHAR(50) NOT NULL UNIQUE,
--SaleTime DATETIME NOT NULL,
--ExgTime DATETIME NOT NULL,
--ExgGoodID NVARCHAR(50) NOT NULL,
--ExgGoodName NVARCHAR(255) NOT NULL,
--ExgGoodNum INT NOT NULL,
--Operator CHAR(4) NOT NULL,
--CONSTRAINT CK_ExgGood CHECK(LEN(SaleTime)>0 AND LEN(ExgTime)>0 AND LEN(ExgGoodID)>0 AND LEN(ExgGoodName)>0 AND 
--LEN(ExgGoodNum)>0 AND LEN(Operator)>0 AND ExgGoodNum>0),
--FOREIGN KEY (Operator)  REFERENCES Staff(StaffID)
--)
--GO